-- TradesWithMe V4.1.1 persistence + adaptive-learning schema
-- Run this in Supabase SQL Editor. Safe to re-run.

create table if not exists public.twm_scans (
  id bigint generated by default as identity primary key,
  scanned_at timestamptz not null,
  regime text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists twm_scans_scanned_at_idx on public.twm_scans (scanned_at desc);


-- The owner's last manually confirmed watchlist, holdings and risk settings.
-- Scheduled scans use this row so overnight correlation/risk checks reflect the personal portfolio.
create table if not exists public.twm_owner_state (
  id text primary key,
  symbols jsonb not null default '[]'::jsonb,
  positions jsonb not null default '[]'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- A frozen, server-side ledger of actionable signals. The unique constraint prevents
-- repeated manual scans on the same completed bar from rewriting the historical record.
create table if not exists public.twm_forward_signals (
  id bigint generated by default as identity primary key,
  opened_at timestamptz not null,
  entry_date date not null,
  symbol text not null,
  asset_class text not null check (asset_class in ('EQUITY','CRYPTO')),
  source text not null,
  entry numeric not null,
  stop numeric,
  target numeric,
  score numeric not null,
  evidence_score numeric not null,
  confidence numeric not null,
  horizon_bars integer not null default 5,
  outcome text not null default 'PENDING' check (outcome in ('PENDING','TARGET','STOP','TIME_EXIT')),
  exit_date date,
  exit_price numeric,
  return_pct numeric,
  bars_held integer,
  agent_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique(symbol, entry_date)
);

create index if not exists twm_forward_signals_opened_at_idx on public.twm_forward_signals (opened_at desc);
create index if not exists twm_forward_signals_outcome_idx on public.twm_forward_signals (outcome);
create index if not exists twm_forward_signals_symbol_idx on public.twm_forward_signals (symbol, entry_date desc);

-- These tables are deliberately server-only. Vercel uses SUPABASE_SERVICE_ROLE_KEY.
alter table public.twm_scans enable row level security;
alter table public.twm_owner_state enable row level security;
alter table public.twm_forward_signals enable row level security;


-- V4.1 shadow ledger: high-quality WATCH candidates are frozen even when they are not
-- actionable. They are evaluated after the horizon and used only to improve agent
-- weighting/calibration. They do NOT count toward the actionable Forward Trust score.
create table if not exists public.twm_shadow_signals (
  id bigint generated by default as identity primary key,
  opened_at timestamptz not null,
  entry_date date not null,
  symbol text not null,
  asset_class text not null check (asset_class in ('EQUITY','CRYPTO')),
  source text not null,
  entry numeric not null,
  score numeric not null,
  evidence_score numeric not null,
  confidence numeric not null,
  horizon_bars integer not null default 5,
  outcome text not null default 'PENDING' check (outcome in ('PENDING','TIME_EXIT')),
  exit_date date,
  exit_price numeric,
  return_pct numeric,
  bars_held integer,
  agent_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique(symbol, entry_date)
);

create index if not exists twm_shadow_signals_opened_at_idx on public.twm_shadow_signals (opened_at desc);
create index if not exists twm_shadow_signals_outcome_idx on public.twm_shadow_signals (outcome);
alter table public.twm_shadow_signals enable row level security;

-- V4.1 adaptive-learning state. The learner stores bounded strategy-weight/calibration
-- updates derived only from completed forward signals. It does not store broker secrets.
create table if not exists public.twm_learning_state (
  id text primary key,
  version integer not null default 1,
  trained_at timestamptz not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.twm_learning_runs (
  id bigint generated by default as identity primary key,
  trained_at timestamptz not null,
  version integer not null,
  sample_count integer not null default 0,
  mode text not null check (mode in ('COLD_START','SHADOW','ADAPTIVE','FROZEN')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists twm_learning_runs_trained_at_idx on public.twm_learning_runs (trained_at desc);

alter table public.twm_learning_state enable row level security;
alter table public.twm_learning_runs enable row level security;

-- V4.1 autonomous-learning observatory. Each scheduled cycle records whether it
-- settled observations, trained the policy, scanned the market, and persisted new
-- frozen observations. This powers the no-click Learning Observatory dashboard.
create table if not exists public.twm_automation_runs (
  id bigint generated by default as identity primary key,
  ran_at timestamptz not null default now(),
  status text not null check (status in ('OK','DEGRADED','FAILED')),
  actionable_settled integer not null default 0,
  shadow_settled integer not null default 0,
  actionable_inserted integer not null default 0,
  shadow_inserted integer not null default 0,
  learning_version integer,
  learning_mode text,
  effective_samples numeric,
  regime text,
  crypto_regime text,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists twm_automation_runs_ran_at_idx on public.twm_automation_runs (ran_at desc);
alter table public.twm_automation_runs enable row level security;


-- V4.1.1: explicit backend grants. Secret keys map to the service_role Postgres role.
grant usage on schema public to service_role;
grant all privileges on table public.twm_scans to service_role;
grant all privileges on table public.twm_owner_state to service_role;
grant all privileges on table public.twm_forward_signals to service_role;
grant all privileges on table public.twm_shadow_signals to service_role;
grant all privileges on table public.twm_learning_state to service_role;
grant all privileges on table public.twm_learning_runs to service_role;
grant all privileges on table public.twm_automation_runs to service_role;
grant usage, select on all sequences in schema public to service_role;
